name: Build mod

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch code
        uses: actions/checkout@v4

      - name: Add SMAPI build environment
        uses: Pathoschild/SMAPI-ModBuildWorkflow/add-build-environment@v1

      - name: Build mod
        run: dotnet build --configuration Release

      - name: Upload mod zip
        uses: actions/upload-artifact@v4
        with:
          name: ChestsAnywhereMobileNav
          path: _releases/*.zip
          if-no-files-found: error
